### ISSUE TITLE
Official support for .NET 5.0

### ISSUE THREAD

**Issue by JimmyCushnie** [JimmyCushnie/SUCC#30]

**Comment by Ruthenic** [comment]
![image](https://user-images.githubusercontent.com/53356436/95245028-888ddf80-07e0-11eb-9420-98249b01dc77.png)
The project appears to build properly in a preview release of .NET 5.0 in the docker container from Microsoft. Will have to do some testing to confirm that it fully works

**Comment by Ruthenic** [comment]
![image](https://user-images.githubusercontent.com/53356436/95245475-2bdef480-07e1-11eb-94c4-6c42a591a8a6.png)
When attempting to run `dotnet test` to run unit tests, the tests fail to build, but SUCC appears to be fine itself? will do some further digging

**Comment by JimmyCushnie** [comment]
yeah ok it works in .net 6 now
